version: '3.7'


services:
  backend:
    build:
     context: ./backend
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - database
      
volumes:
  postgres_data:
    driver: local