"""update cities table

Revision ID: 0442943768cd
Revises: 8455ef778d6d
Create Date: 2024-07-20 13:04:18.302202

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0442943768cd"
down_revision: Union[str, None] = "8455ef778d6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cities", "lng", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "cities", "lat", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cities", "lat", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "cities", "lng", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    # ### end Alembic commands ###
