"""update cities table on name fields

Revision ID: 0f15980739c2
Revises: 0442943768cd
Create Date: 2024-07-20 13:16:19.484230

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0f15980739c2'
down_revision: Union[str, None] = '0442943768cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'name_eng',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               nullable=True)
    op.alter_column('cities', 'name_uk',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               nullable=True)
    op.alter_column('cities', 'name_ru',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'name_ru',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cities', 'name_uk',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cities', 'name_eng',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
