"""create cities table

Revision ID: 8455ef778d6d
Revises: 
Create Date: 2024-07-19 22:01:47.380297

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8455ef778d6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('STATE', 'DISTRICT', 'CAPITAL_CITY', 'CITY', 'VILLAGE', name='locationtypeenum'), nullable=False),
    sa.Column('name_eng', sa.String(length=50), nullable=False),
    sa.Column('name_uk', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('post_code', sa.String(length=10), nullable=True),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('katottg', sa.String(length=19), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
